version: '3'

services:
  test:
    build: .
    volumes:
      - .:/usr/src/app
    command: bundle exec rake test
    volumes:
      - type: bind
        source: '.'
        target: '/usr/src/app'

volumes:
  gem_cache:
