version: '3'

services:
  test:
    build: .
    volumes:
      - .:/usr/src/app
      - gem_cache:/gems
    command: "bundle exec rake test"
    deploy:
      restart_policy:
        condition: none

volumes:
  gem_cache:
