version: '3'

services:
  test:
    build: .
    volumes:
      - .:/usr/src/app
    command: bash -c "bundle exec rake test && bundle exec rubocop"
    volumes:
      - type: bind
        source: '.'
        target: '/usr/src/app'

volumes:
  gem_cache:
