feed_validate_script: '/l/local/feed/bin/validate_images.pl'
stages:
  - name: Preflight
    class: Preflight
    file: preflight
  - name: TIFF Validator
    class: TIFFValidator
    file: tiff_validator
  - name: Pagination Check
    class: PaginationCheck
    file: pagination_check
  - name: Tagger
    class: Tagger
    file: tagger
  - name: Compressor
    class: Compressor
    file: compressor
  - name: Postflight
    class: Postflight
    file: postflight


